# Generated by Django 2.2 on 2020-10-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='user',
        ),
    ]
